backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Статьи"
    label_singular: "Статья"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", value_type: "int"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "URL-адрес", name: "slug", widget: "string"}
      - {label: "Краткое описание", name: "excerpt", widget: "text"}
      - {label: "Автор", name: "author", widget: "string"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Иконка", name: "icon", widget: "string"}
      - {label: "Категория", name: "category", widget: "select", options: ["идентичность", "история", "культура"]}
      - {label: "Теги", name: "tags", widget: "list"}
      - {label: "Изображение превью", name: "previewImage", widget: "string"}
      - {label: "Содержание", name: "content", widget: "markdown"}