backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Статьи"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Автор", name: "author", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Категория", name: "category", widget: "select", options: ["идентичность", "история", "культура"] }
      - { label: "Краткое описание", name: "excerpt", widget: "text" }
      - { label: "Изображение предпросмотра", name: "previewImage", widget: "image" }
      - { label: "Содержание", name: "content", widget: "markdown" }
      - { label: "Теги", name: "tags", widget: "list", default: [] }